Implementation of split real/virtual packet tunnel in WireGuardGo for IAN
mullvad/wireguard-apple pull request #10
Opened 2024-06-20 10:14 UTC by acb-mv

2024-06-20 20:44 UTC, pinkisemils commented
@Serock3 and @mvd-ows, would be great if you could take a look at these changes. Since a description is lacking here, the main goal of these changes is to prep the WireGuard go shim for virtual networking. Due to _reasons_, we have to inject our own traffic into the tunnel, whilst still tunneling user traffic. To do this, we have chosen to use gvisor's userspace IP stack and implement our own  `tun.Device` interface that multiplexes between these two tunnel devices - the one we get from the system for user traffic and the userspace tunnel device for our own traffic. The virtual networking isn't used for anything *yet*, but soon it will be used to reach the tunnel config service and for ICMP too.

@buggmagnet Do review the swift changes intently, and peruse the go changes at will.

2024-06-24 08:04 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @mvd-ows)

___
*[`Sources/WireGuardKitGo/router.go` line 56 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FGuOAtUabdiju5U1:-O08FGuOAtUabdiju5U2:b-fyhyzv) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L56)):*
> ```Go
> // BatchSize implements tun.Device.
> func (r *Router) BatchSize() int {
> 	return r.real.BatchSize()
> ```

Having thought about this long and hard, we should probably use a batch size of 128. Underruns just cost more static memory, overruns cost us more allocs since then we have to keep the overflow around.
___
*[`Sources/WireGuardKitGo/router.go` line 61 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08EruH9Fd1LKFZocGh:-O08EruH9Fd1LKFZocGi:bgzmelx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L61)):*
> ```Go
> // Close implements tun.Device.
> func (r *Router) Close() error {
> 	// TODO: anything else we need to shut down here
> ```

We should probably add a test that checks for active go routines, as it's done in `wireguard-go` device tests too. https://github.com/WireGuard/wireguard-go/blob/master/device/device_test.go#L395-L421

Then we can be certain we are not leaking anything too.
___
*[`Sources/WireGuardKitGo/router.go` line 103 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FWeU6U2TA7WXecLL:-O08FWeU6U2TA7WXecLM:bb61qeh) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L103)):*
> ```Go
> type PacketIdentifier [22]byte
> 
> func humanReadableForm(pi PacketIdentifier) string {
> ```

This function isn't used anywhere anymore.
___
*[`Sources/WireGuardKitGo/router.go` line 126 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FeBq1luJTOFd6A1n:-O08FeBq1luJTOFd6A1o:b-nog57t) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L126)):*
> ```Go
> const ProtocolUDP = 17
> 
> func getPorts(protocol byte, protocolHeader []byte) (uint16, uint16) {
> ```

The return arguments could be named to indicate what they mean. Or this could have a comment explaining what they mean, currently, it's very obtuse.
___
*[`Sources/WireGuardKitGo/router.go` line 164 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FsWGDbHcFeo-w1wR:-O08FsWGDbHcFeo-w1wS:bm5l8ca) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L164)):*
> ```Go
> 	}
> 	// TODO: skip the chain of IPv6 extension headers to get to the ports.
> 	// For now, we just ignore them and assume no ports if there are extension headers
> ```

There is a very useful library that we already depend on here - https://pkg.go.dev/gvisor.dev/gvisor/pkg/tcpip/header
This will parse the IPv6 and IPv4 headers properly. Would allow us to remove this _TODO_. 


<!-- Sent from Reviewable.io -->

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +		return -1
Consider defining public constant values to use as error codes. This looks very brittle, especially given the number of unique errors you have.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +	vtun, virtualNet, err := netstack.CreateNetTUN([]netip.Addr{privateAddr}, []netip.Addr{}, 1280)
That's a very low value for MTU. Is this adjusted after the device has been created?

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +	if virtualNet == nil {
Why do you need to check `virtualNet` but not `vtun`?

If in some scenarios `CreateNetTUN()` can be said to have succeeded without returning a valid `virtualNet`, perhaps it would be more clear to instead return a *struct that holds `vtun` and `virtualNet`. The latter could then be pointer, and with applicable comments included about what to expect.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +		unix.Close(dupTunFd)
`dupTunFd` is probably owned by `tun` at this point. Or you could just unconditionally close it after the call to `CreateTUNFromFile()`.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +		unix.Close(dupTunFd)
Ownership, see above.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/api-apple.go
> +	for i = 0; i < math.MaxInt32; i++ {
Nit: I realize this works, but "handles" are typically never `0`.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +func (pb *PacketBatch) truncate(headsize int, make_batch func() *PacketBatch) *PacketBatch {
The name `make_batch` is not idiomatic. `makeBatch` would be preferred.

Consider adding a simple comment that explains why it's needed. I assume it's so the uninitialized instance being returned can be tracked elsewhere.

Nit: Also consider if there is a better name to use than `truncate`. I see two issues: First, in a truncate operation the waste it typically discarded. Second, at a quick glance, one might assume that `pb` is immutable and that the returned instance is actually a truncated version of the data.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	overflowSize := len(pb.packets) - headsize
This looks weird. The computation is "count minus length". Perhaps there's a good reason?

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	virtualRouteChan    chan PacketIdentifier
This is to ensure a single entity accesses the maps, right? Perhaps related data and logic could be placed in a separate private component (struct).

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	r.rxShutdown <- struct{}{}
You should wait for the cancelled workers to complete.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	protocol   byte
Consider whether there should be a specific type to represent the protocol.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +const ProtocolICMP = 1
These constants should be available elsewhere already. But perhaps this saves an import.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	case ProtocolTCP:
You can actually do `case ProtocolTCP, ProtocolUDP:` to fold the cases. Consider using `binary.BigEndian.Uint16()`.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	headerLength := (packet[0] & 0xff) * 4
`int(packet[0]) * 4` may be more clear.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +func getPorts(protocol byte, protocolHeader []byte) (uint16, uint16) {
Consider ensuring that the slice passed has enough data in it.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	var destAddress netip.Addr
Consider ensuring that the slice passed has enough data in it.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	protocol := packet[9]
Do you not need to validate `protocol` to ensure that the parsing below is applicable?

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +func fillPacketHeaderData(packet []byte, packetHeaderData *PacketHeaderData, offset int, isIncoming bool) bool {
Can't you subslice the packet on the outside and send one less argument?

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	r.rxVirtualRoutes[identifier] = true
The standard map type is not safe for concurrent read/write. Not sure if applicable.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +		return rw, err
Consider whether you should attempt to write to the virtual device as well, even when the primary write has failed.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +	return rw + vw, err
Consider whether you should avoid relying on `rw` and `vw` being `0` in case of error. By convention, they are undefined.

2024-06-24 11:05 UTC, mvd-ows commented on Sources/WireGuardKitGo/router.go
> +		buffer[idx] = make([]byte, 1500+maxOffset)
Using `1500` seems reasonable, but can be problematic. Most code that needs to store UDP packets allocate the maximum allowed size, which is 65K.

2024-06-24 11:36 UTC, buggmagnet reviewed
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 39 unresolved discussions (waiting on @acb-mv and @MarkusPettersson98)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 152 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08K2OF0VHUtsoxM_GO:-O08K2OF0VHUtsoxM_GP:b8mupja) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L152)):*
> ```Go
> 	}
> 
> 	dupTunFd, err := unix.Dup(int(tunFd))
> ```

We should check that `tunFd > 0` before calling `dup` on it
We also need to guarantee that `tunFD < getdtablesize()`, so we should fail in that case too.

I just noticed we don't do those checks in the `wgTurnOn` function either, we definitely should.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 175 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08Tg403JzDBSvE1kj4:-O08Tg403JzDBSvE1kj5:b-j3xxbc) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L175)):*
> ```Go
> 	if err != nil {
> 		logger.Errorf("Failed to initialize virtual tunnel device: %v", err)
> 		return -5
> ```

missing `unix.Close(dupTunFd)`
___
*[`Sources/WireGuardKitGo/api-apple.go` line 180 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08ThDWAzEPnVQJ1dO1:-O08ThDWAzEPnVQJ1dO2:b-o5b8xk) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L180)):*
> ```Go
> 	if virtualNet == nil {
> 		logger.Errorf("Failed to initialize virtual tunnel device")
> 		return -6
> ```

missing `unix.Close(dupTunFd)` 
___
*[`Sources/WireGuardKitGo/api-apple.go` line 208 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08XE_t2K3RjePBI1KB:-O08XE_t2K3RjePBI1KC:bqjiym) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L208)):*
> ```Go
> 	}
> 	tunnelHandles[i] = tunnelHandle{dev, logger}
> 	// TODO: add a tunnel handle, or otherwise make sure we can create connections in the tunnel
> ```

We want to make sure we don't lose `virtualNet` here
___
*[`Sources/WireGuardKitGo/go.mod` line 20 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08GZtW1mAgH4nbO_ii:-O08GZtW1mAgH4nbO_ij:b-izm86i) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/go.mod#L20)):*
> ```XML
> 	golang.zx2c4.com/wintun v0.0.0-20230126152724-0fa3db229ce2 // indirect
> 	gopkg.in/yaml.v3 v3.0.1 // indirect
> 	gvisor.dev/gvisor v0.0.0-20230927004350-cbd86285d259 // indirect
> ```

This will require us moving to go 1.20, we should make sure to track that change in the mullvad codebase.
___
*[`Sources/WireGuardKitGo/router.go` line 16 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08Y3rR8ZskyRcItfW2:-O08Y3rS2YImOYxcfwX0:b3xnzc0) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L16)):*
> ```Go
> )
> 
> const maxOffset = 128
> ```

The name doesn't exactly say how it's used. 
Can we clarify it ?
___
*[`Sources/WireGuardKitGo/router.go` line 17 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08YtB260hTKVJnh48W:-O08YtB260hTKVJnh48X:bm5drug) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L17)):*
> ```Go
> 
> const maxOffset = 128
> const expectedBufferCount = 1
> ```

Should we use instead `conn.IdealBatchSize` here ?
___
*[`Sources/WireGuardKitGo/router.go` line 62 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08aqWcC8_LewVwlm4x:-O08aqWcC8_LewVwlm4y:b6mfdjd) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L62)):*
> ```Go
> func (r *Router) Close() error {
> 	// TODO: anything else we need to shut down here
> 	r.rxShutdown <- struct{}{}
> ```

Let's add a comment explaining why we have the same line repeated twice, to make sure we don't think it's a bug in the future if it's intentional
___
*[`Sources/WireGuardKitGo/router.go` line 68 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08c6gQ2w0y1mLdC6x-:-O08c6gQ2w0y1mLdC6x0:bg42zvp) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L68)):*
> ```Go
> 	if err1 != nil {
> 		return err1
> 	} else {
> ```

We can remove this else statement here
___
*[`Sources/WireGuardKitGo/router.go` line 100 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08dMiL1gNs8IncbGwU:-O08dMiL1gNs8IncbGwV:b-9a363n) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L100)):*
> ```Go
> }
> 
> // type (1 byte) + padding (1 byte) + src port (2 bytes) + dest addr + dest port
> ```

This should be `protocol` instead of `type`, or maybe `protocol type` 
___
*[`Sources/WireGuardKitGo/router.go` line 101 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08cP7O6u3eM41T5FFp:-O08cP7O6u3eM41T5FFq:b88q9yf) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L101)):*
> ```Go
> 
> // type (1 byte) + padding (1 byte) + src port (2 bytes) + dest addr + dest port
> type PacketIdentifier [22]byte
> ```

We should specify that `dest addrs` can either be 8 or 16 bytes (for IPv6) which is why the total size is 22
___
*[`Sources/WireGuardKitGo/router.go` line 117 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08hkw1D1TN46zUyxSE:-O08hkw24hnnY4vS7S5p:b-4fh8dn) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L117)):*
> ```Go
> 	result[0] = pi.protocol
> 	copy(result[4:], destAddrBytes[:])
> 	binary.BigEndian.PutUint16(result[2:], pi.sourcePort)
> ```

Should we make sure that the `padding` is set correctly as well ?
```go
result[1] = 0
```
___
*[`Sources/WireGuardKitGo/router.go` line 296 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08aZmI3yo4CCruD2Dm:-O08aZmJCmlRFDCsY3IU:buc2f1a) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L296)):*
> ```Go
> 		_, err := device.Read(batch.packets, batch.sizes, maxOffset)
> 		if err != nil {
> 			return
> ```

We leak the `batch` we just got from the pool here


<!-- Sent from Reviewable.io -->

2024-06-24 12:01 UTC, acb-mv commented on Sources/WireGuardKitGo/api-apple.go
> +		return -1
These error codes were only used for tracing a bug. We can probably just make them all `-1`

2024-06-24 12:57 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, and @mvd-ows)

___
*[`Sources/WireGuardKitGo/router.go` line 155 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O092dhP8Es2VKZ5-Hg9:-O092dhP8Es2VKZ5-HgA:bu38f1q) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L155)):*
> ```Go
> 	var destAddress netip.Addr
> 	var srcPort, destPort uint16
> 	nextHeader := packet[6]
> ```

Shouldn't this be `protocol` ? That's how it ends up being used, it makes it hard to follow that it has a name that has not much to do with the notion of `protocol`, especially given that the v4 version of this function names it protocol.
___
*[`Sources/WireGuardKitGo/router.go` line 195 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O094Ue85GMGzKn5jfmi:-O094Ue85GMGzKn5jfmj:bnhv8p1) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L195)):*
> ```Go
> 		return 0, fmt.Errorf("illegal offset %d > %d", offset, maxOffset)
> 	}
> 	var packets *PacketBatch
> ```

This should really be renamed `packetsBatch`, otherwise it makes the code down the line really hard to read
`range packets.packets` for example.


<!-- Sent from Reviewable.io -->

2024-06-24 13:38 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 62 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08aqWcC8_LewVwlm4x:-O09Rp-IByI52i6HpAnJ:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L62)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's add a comment explaining why we have the same line repeated twice, to make sure we don't think it's a bug in the future if it's intentional
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 68 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08c6gQ2w0y1mLdC6x-:-O09RrMEBAbYS8Jh1IZs:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L68)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove this else statement here
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 100 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08dMiL1gNs8IncbGwU:-O09Rvpp4_pRMmgmvhV-:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L100)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be `protocol` instead of `type`, or maybe `protocol type`
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 101 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08cP7O6u3eM41T5FFp:-O09RxF94saGU9coZCM1:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L101)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should specify that `dest addrs` can either be 8 or 16 bytes (for IPv6) which is why the total size is 22
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 103 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FWeU6U2TA7WXecLL:-O09RyBO5HObKotW2xi2:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L103)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This function isn't used anywhere anymore.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 117 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08hkw1D1TN46zUyxSE:-O09S--m-mrFQpq4hcXQ:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L117)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Should we make sure that the `padding` is set correctly as well ?
```go
result[1] = 0
```
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 141 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650769854:-O09SIyNDHhdSi9XE2cV:b-69rh0l) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L141)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Do you not need to validate `protocol` to ensure that the parsing below is applicable?
</blockquote></details>

No, source and destination IPs in an IPv4 header are protocol-independent
___
*[`Sources/WireGuardKitGo/router.go` line 168 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650777701:-O09SymnE74Gp_FoDDCK:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L168)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Can't you subslice the packet on the outside and send one less argument?
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 296 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08aZmI3yo4CCruD2Dm:-O09T2Z2BRr8eA7gag8r:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L296)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We leak the `batch` we just got from the pool here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-24 13:59 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 40 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 141 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650769854:-O09Wa_zET6eUDLpHZZN:bbigurr) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L141)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

No, source and destination IPs in an IPv4 header are protocol-independent
</blockquote></details>

Right, my bad. I forgot that you assume IPv4 in this function and figured you were reading the header type of the header currently being parsed. Which also doesn't make any sense because the Ethernet header is not exposed to WireGuard. Carry on :-)


<!-- Sent from Reviewable.io -->

2024-06-24 14:32 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 39 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 16 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08Y3rR8ZskyRcItfW2:-O09bA8H7qAUpj_dNuaR:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The name doesn't exactly say how it's used. 
Can we clarify it ?
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 26 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650607934:-O09cTua2S8rgqlurscf:bmbkioe) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L26)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The name `make_batch` is not idiomatic. `makeBatch` would be preferred.

Consider adding a simple comment that explains why it's needed. I assume it's so the uninitialized instance being returned can be tracked elsewhere.

Nit: Also consider if there is a better name to use than `truncate`. I see two issues: First, in a truncate operation the waste it typically discarded. Second, at a quick glance, one might assume that `pb` is immutable and that the returned instance is actually a truncated version of the data.
</blockquote></details>

Mostly done. 
I could call it `split`, though that's even more vague as to intention (and sounds like a list/string operation). More colloquially, the term `haircut` comes to mind (as used as a metaphor, for example in finance), but that also sounds silly and requires an explanation. `truncate` seems descriptive. Perhaps `truncateReturningOverflow` or similar if we need more disambiguation?
___
*[`Sources/WireGuardKitGo/router.go` line 56 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FGuOAtUabdiju5U1:-O09dE9w7OpWPD1SSJVu:b6n5oki) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L56)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Having thought about this long and hard, we should probably use a batch size of 128. Underruns just cost more static memory, overruns cost us more allocs since then we have to keep the overflow around.
</blockquote></details>

That's all very well, except that wireGuardGo seems to feed us the packets one at a time.


<!-- Sent from Reviewable.io -->

2024-06-24 14:36 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 39 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 155 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O092dhP8Es2VKZ5-Hg9:-O09f7uw4ADlVUmEQ66V:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L155)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't this be `protocol` ? That's how it ends up being used, it makes it hard to follow that it has a name that has not much to do with the notion of `protocol`, especially given that the v4 version of this function names it protocol.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-24 15:14 UTC, buggmagnet requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 42 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 261 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09N6qn0FVcXIz-qvgI:-O09N6qo05W8hlA4Y7KC:b-6vvqxe) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L261)):*
> ```Go
> 	}
> 
> 	rw := 0
> ```

Can we rename those `realWrites` and `virtualWrites` ?
It's really hard to follow otherwise
___
*[`Sources/WireGuardKitGo/router.go` line 232 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09jeb721rKxLigSY85:-O09jeb721rKxLigSY86:b9xgg4u) ([raw file](https://github.com/mullvad/wireguard-apple/blob/3dd20849e40030b6c673e5f68c3b9820d7b16288/Sources/WireGuardKitGo/router.go#L232)):*
> ```Go
> 
> 	headerData := PacketHeaderData{}
> 	// realPackets := initializeWritePacketBuffer(len(bufs))
> ```

Let's remove those comments if we don't intend to use the code.
___
*[`Sources/WireGuardKitGo/router.go` line 263 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09hoL5BC9kEXj3um65:-O09hoL5BC9kEXj3um66:bb4nkhd) ([raw file](https://github.com/mullvad/wireguard-apple/blob/3dd20849e40030b6c673e5f68c3b9820d7b16288/Sources/WireGuardKitGo/router.go#L263)):*
> ```Go
> 		vw, err = r.virtual.Write(r.writeVirtualPackets, offset)
> 	}
> 	return rw + vw, err
> ```

There's no chance that this should overflow, but let's add a comment that says that we know it cannot for safety's sake.


<!-- Sent from Reviewable.io -->

2024-06-24 21:52 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @mvd-ows)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 152 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08K2OF0VHUtsoxM_GO:-O0Aea428KN45JdMUP_G:bjx2mx3) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L152)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should check that `tunFd > 0` before calling `dup` on it
We also need to guarantee that `tunFD < getdtablesize()`, so we should fail in that case too.

I just noticed we don't do those checks in the `wgTurnOn` function either, we definitely should.
</blockquote></details>

What is the point? `unix.Dup` returns an error already.  In the case that it fails, we already check the error.

Moreover, if it fails, the only reason not to cause a `panic` would be to not leak. All bets are off if the process has ~5109 file descriptors. 
After having run some experiments, even when at a file descriptor limit, `dup` just works, and works well. I can only imagine that the man page is outdated. 
___
*[`Sources/WireGuardKitGo/api-apple.go` line 171 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650566845:-O0AdrrA1zgfKZR_OQo2:burycwg) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L171)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

That's a very low value for MTU. Is this adjusted after the device has been created?
</blockquote></details>

We currently use 1280 everywhere on iOS, this is as per design, because iOS is slightly broken. 
___
*[`Sources/WireGuardKitGo/api-apple.go` line 175 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08Tg403JzDBSvE1kj4:-O0BDsNyBwE0Y7x2_ybv:btlui9) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L175)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

missing `unix.Close(dupTunFd)`
</blockquote></details>

At this point, the file descriptor is already owned by the wireguard device, closing it would result in a double free, so this is a very dangerous suggestion. 
___
*[`Sources/WireGuardKitGo/api-apple.go` line 190 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650581918:-O0Ade0U9dWAT_ePlw6G:brt8mnx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L190)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`dupTunFd` is probably owned by `tun` at this point. Or you could just unconditionally close it after the call to `CreateTUNFromFile()`.
</blockquote></details>

At this point, `dev` owns the `Device` anyway, so it really should call `dev.Close()`.
___
*[`Sources/WireGuardKitGo/router.go` line 101 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08cP7O6u3eM41T5FFp:-O09osTw5ulVIDZzEMLS:b-ezd6ld) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L101)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`dest addr` can be either 4 or 16 bytes, not 8. But we will always use a 16 byte representation. So I'd argue it's best to just say `16 bytes`, end of.
___
*[`Sources/WireGuardKitGo/router.go` line 164 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FsWGDbHcFeo-w1wR:-O08Ih3y7c47BGreDVk8:b-umbe5u) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L164)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

There is a very useful library that we already depend on here - https://pkg.go.dev/gvisor.dev/gvisor/pkg/tcpip/header
This will parse the IPv6 and IPv4 headers properly. Would allow us to remove this _TODO_.
</blockquote></details>

lol
lmao
What that package does is practically the same as what we're doing anyway.
___
*[`Sources/WireGuardKitGo/router.go` line 185 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650786992:-O09pF5RAGwmR3Uz26eY:b-rl321p) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L185)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The standard map type is not safe for concurrent read/write. Not sure if applicable.
</blockquote></details>

There are two distinct maps, one for the read side and one for the write side. They should only ever be read and modified by one go routine. 
___
*[`Sources/WireGuardKitGo/router.go` line 263 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09hoL5BC9kEXj3um65:-O0AdJWf8W23lEeX3g7_:b-u8zx5o) ([raw file](https://github.com/mullvad/wireguard-apple/blob/3dd20849e40030b6c673e5f68c3b9820d7b16288/Sources/WireGuardKitGo/router.go#L263)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There's no chance that this should overflow, but let's add a comment that says that we know it cannot for safety's sake.
</blockquote></details>

I really don't think we should be doing this. 


<!-- Sent from Reviewable.io -->

2024-06-25 08:49 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 261 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09N6qn0FVcXIz-qvgI:-O0DUC1C94iWhW7yXROE:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L261)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we rename those `realWrites` and `virtualWrites` ?
It's really hard to follow otherwise
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 268 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650805170:-O0DUO0-0weVNUCeFfSk:bjop1dr) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L268)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider whether you should attempt to write to the virtual device as well, even when the primary write has failed.
</blockquote></details>

The real and virtual devices are on the client side, and should be closed at the same time. Though if they're not for some reason and there is some incoming data to the virtual device, it is IMHO not the router's concern to cut that off.
___
*[`Sources/WireGuardKitGo/router.go` line 273 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650811101:-O0DV0h20aDEs_nSiuiZ:b-59f3ir) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L273)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider whether you should avoid relying on `rw` and `vw` being `0` in case of error. By convention, they are undefined.
</blockquote></details>

I'll zero `virtualWritten` in case of error so that it doesn't throw the count. In our case, it is possible that we successfully wrote some packets but got an error subsequently. Presumably the caller will ignore the count in case of error, but, all effort being equal, delivering the most accurate trivially obtainable count probably makes more sense than just zeroing the whole thing. (Given Go's lack of ternary operators, doing the latter would mean another 3-line if statement, further cluttering the code without particularly good reason.)
___
*[`Sources/WireGuardKitGo/router.go` line 232 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09jeb721rKxLigSY85:-O0DU16F8o4W0tTtPIfb:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/3dd20849e40030b6c673e5f68c3b9820d7b16288/Sources/WireGuardKitGo/router.go#L232)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's remove those comments if we don't intend to use the code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 09:36 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/api-apple.go` line 190 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650581918:-O0Dk9kL1y-GBPSo9Dau:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L190)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

At this point, `dev` owns the `Device` anyway, so it really should call `dev.Close()`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-25 12:36 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 175 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08Tg403JzDBSvE1kj4:-O0EAiLsD6mjg3ivsVlz:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L175)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

At this point, the file descriptor is already owned by the wireguard device, closing it would result in a double free, so this is a very dangerous suggestion.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 178 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650569164:-O0EAlb1CXm_y9xePk00:b-cll1b9) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L178)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Why do you need to check `virtualNet` but not `vtun`?

If in some scenarios `CreateNetTUN()` can be said to have succeeded without returning a valid `virtualNet`, perhaps it would be more clear to instead return a *struct that holds `vtun` and `virtualNet`. The latter could then be pointer, and with applicable comments included about what to expect.
</blockquote></details>

`vtun` and `virtualNet` are the same value, though being returned with different interfaces.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 180 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08ThDWAzEPnVQJ1dO1:-O0EAziU-O9Z8iH8q1DO:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L180)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

missing `unix.Close(dupTunFd)`
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 208 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08XE_t2K3RjePBI1KB:-O0ED1aoDTsz9CeLjnwL:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L208)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We want to make sure we don't lose `virtualNet` here
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 17 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08YtB260hTKVJnh48W:-O0EDqXF6VbYnQX-ReCc:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Should we use instead `conn.IdealBatchSize` here ?
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 94 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650738333:-O0EJWIq85fznUA7E6AE:b-mrh1kz) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L94)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider whether there should be a specific type to represent the protocol.
</blockquote></details>

This has now been replaced with `gvisor`'s `tcpip.TransportProtocolNumber`
___
*[`Sources/WireGuardKitGo/router.go` line 122 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650744693:-O0EJhls-Lth3FvOR-kL:b-ngdhem) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L122)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

These constants should be available elsewhere already. But perhaps this saves an import.
</blockquote></details>

Good catch. We depend on GVisor (via WireGuardGo), so we have now imported its version of these constants.
___
*[`Sources/WireGuardKitGo/router.go` line 126 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08FeBq1luJTOFd6A1n:-O0EKIlJ1Ar0wFeYAata:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L126)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The return arguments could be named to indicate what they mean. Or this could have a comment explaining what they mean, currently, it's very obtuse.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 126 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650768048:-O0ELxdy9Qo5tgCl1BH9:b-f41wfg) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L126)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider ensuring that the slice passed has enough data in it. 
</blockquote></details>

the `getPacketHeaderData*` functions have been refactored to accept a pointer to the structure to fill and return a boolean value, checking the input size, which takes care of this issue.
___
*[`Sources/WireGuardKitGo/router.go` line 128 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650751117:-O0EMCXP7cF07AZUCJYh:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L128)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

You can actually do `case ProtocolTCP, ProtocolUDP:` to fold the cases. Consider using `binary.BigEndian.Uint16()`.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 138 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650768171:-O0EMF9tC-Bx_g0eZmax:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L138)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider ensuring that the slice passed has enough data in it. 
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 140 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650761985:-O0EMNUXDmBq36DeY_hK:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L140)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`int(packet[0]) * 4` may be more clear.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 195 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O094Ue85GMGzKn5jfmi:-O0EMqe318hb9HW7C0zA:b-e4nnhg) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L195)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should really be renamed `packetsBatch`, otherwise it makes the code down the line really hard to read
`range packets.packets` for example.
</blockquote></details>

I've renamed it to `packetBatch`; `packetsBatch` rolls off the tongue awkwardly, and doesn't add any clarity over `packetBatch`
___
*[`Sources/WireGuardKitGo/router.go` line 279 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650815226:-O0ENkY33X7VDLjq5O21:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L279)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Using `1500` seems reasonable, but can be problemat [...]

2024-06-25 14:36 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 46 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650677745:-O0EojoLCo_s2rGGpWxF:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L46)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is to ensure a single entity accesses the maps, right? Perhaps related data and logic could be placed in a separate private component (struct).
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 63 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650694731:-O0EooAL7SrRua2mGZ-b:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L63)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

You should wait for the cancelled workers to complete.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-26 13:29 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 41 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 61 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08EruH9Fd1LKFZocGh:-O0Ji_Na8kormSDRA_Uu:b-5g9vo5) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L61)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We should probably add a test that checks for active go routines, as it's done in `wireguard-go` device tests too. https://github.com/WireGuard/wireguard-go/blob/master/device/device_test.go#L395-L421

Then we can be certain we are not leaking anything too.
</blockquote></details>

Checks have been added, concluding that WireGuardGo's `netstack.tun` appears to be leaking goroutines. This has been documented as issue IOS-739, though its impact appears to be noncatastrophic if not manageable.


<!-- Sent from Reviewable.io -->

2024-06-26 13:41 UTC, mvd-ows commented
*[`Sources/WireGuardKitGo/router.go` line 61 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08EruH9Fd1LKFZocGh:-O0JliV_5Iej80BlX_kk:b-x7fatc) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L61)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Checks have been added, concluding that WireGuardGo's `netstack.tun` appears to be leaking goroutines. This has been documented as issue IOS-739, though its impact appears to be noncatastrophic if not manageable.
</blockquote></details>

Same issue as this one? https://github.com/WireGuard/wireguard-go/pull/101


<!-- Sent from Reviewable.io -->

2024-06-26 13:43 UTC, mvd-ows commented
*[`Sources/WireGuardKitGo/api-apple.go` line 178 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#gh-1650569164:-O0JmF-K12qbHH8CFPbW:b-7aitaz) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L178)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

`vtun` and `virtualNet` are the same value, though being returned with different interfaces.
</blockquote></details>

Thanks for clarifying.


<!-- Sent from Reviewable.io -->

2024-06-26 14:09 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 1 of 7 files reviewed, 23 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 61 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08EruH9Fd1LKFZocGh:-O0Jrzyt8YnECkAQpAlj:b-wmrgwb) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/router.go#L61)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Same issue as this one? https://github.com/WireGuard/wireguard-go/pull/101
</blockquote></details>

Thanks. If we end up forking WireGuardGo, we may fix it ourselves, assuming the maintainers of the upstream branch don't do so.


<!-- Sent from Reviewable.io -->

2024-06-28 07:53 UTC, buggmagnet approved these changes
> Reviewed 1 of 7 files at r1, 1 of 3 files at r8, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 152 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08K2OF0VHUtsoxM_GO:-O0Siq8t-kg_6TgLYI4k:bob89km) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L152)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What is the point? `unix.Dup` returns an error already.  In the case that it fails, we already check the error.

Moreover, if it fails, the only reason not to cause a `panic` would be to not leak. All bets are off if the process has ~5109 file descriptors. 
After having run some experiments, even when at a file descriptor limit, `dup` just works, and works well. I can only imagine that the man page is outdated.
</blockquote></details>

Actually, nevermind, it looks like `getdtablesize` is a very old and obsolete function at this point.
Thanks for running the experiment though.
___
*[`Sources/WireGuardKitGo/router_test.go` line 21 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09oI6gBsIgUW0-7R9I:-O09oI6gBsIgUW0-7R9J:br1kn78) ([raw file](https://github.com/mullvad/wireguard-apple/blob/d4f04e03ece2b1eec199a1d79d7c5ee4285ef4c7/Sources/WireGuardKitGo/router_test.go#L21)):*
> ```Go
> 
> func TestRead(t *testing.T) {
> 	a, _, _ := netstack.CreateNetTUN([]netip.Addr{}, []netip.Addr{}, 1280)
> ```

This doesn't seem to be testing anything, we can safely remove it.


<!-- Sent from Reviewable.io -->

2024-06-28 08:05 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router_test.go` line 21 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O09oI6gBsIgUW0-7R9I:-O0Srz23-qrLDqKoaxUE:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/d4f04e03ece2b1eec199a1d79d7c5ee4285ef4c7/Sources/WireGuardKitGo/router_test.go#L21)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This doesn't seem to be testing anything, we can safely remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-28 20:31 UTC, mvd-ows commented
*[`Sources/WireGuardKitGo/api-apple.go` line 233 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VWjcm2RsWY2eNzAy_:-O0VWjcm2RsWY2eNzAya:b-ugzzoj) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/api-apple.go#L233)):*
> ```Go
> 	err := handle.wireGuardDevice.IpcSet(C.GoString(settings))
> 	if err != nil {
> 		handle.logger.Errorf("Unable to set IPC settings: %v", err)
> ```

This is a slight change compared to before. It probably doesn't make a difference, unless a device's logger can be reassigned. Same with the other calls to `Errorf()` a bit further down.


<!-- Sent from Reviewable.io -->

2024-06-28 22:53 UTC, mvd-ows requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 4 of 7 files reviewed, 12 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 113 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VxYNA9fLN2-mQQLTB:-O0VxYNB1wwO62oEnLIx:b-hl3emd) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L113)):*
> ```Go
> }
> 
> type PacketHeaderData struct {
> ```

Have you considered using `remoteAddr` etc instead of `destAddr`? I find it quite confusing when related code reads the source IP and puts it in `destAddr`.
___
*[`Sources/WireGuardKitGo/router.go` line 225 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VqP5ZBEvCPqvQyISE:-O0VqP5ZBEvCPqvQyISF:b6zz799) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L225)):*
> ```Go
> 	for packetIndex := range packetBatch.packets {
> 
> 		copy(bufs[packetIndex][offset:], packetBatch.packets[packetIndex][maxOffset:])
> ```

What's the purpose of the `maxOffset` subslicing?
___
*[`Sources/WireGuardKitGo/router.go` line 229 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0Vsz_R-WMx2pwbRYhy:-O0Vsz_R-WMx2pwbRYhz:b2nrqz4) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L229)):*
> ```Go
> 
> 		if packetBatch.isVirtual && fillPacketHeaderData(bufs[packetIndex][offset:], &headerData, false) {
> 			r.read.setVirtualRoute(headerData)
> ```

The comment at the start of this function mentions parallel execution. But the function called here is not safe in that context, without using additional locking.
___
*[`Sources/WireGuardKitGo/router.go` line 241 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VvbZI1W36SkWtjkjy:-O0VvbZI1W36SkWtjkjz:b-jnf0rj) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L241)):*
> ```Go
> 		case newVirtualRoute := <-r.virtualRouteChan:
> 			r.virtualRoutes[newVirtualRoute] = true
> 			continue
> ```

Superfluous. There is no fall-through unless explicitly added.
___
*[`Sources/WireGuardKitGo/router.go` line 309 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0W0TYa3F4kQWNXWHUZ:-O0W0TYa3F4kQWNXWHU_:b1qpowa) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L309)):*
> ```Go
> 		if err != nil {
> 			r.batchPool.Put(batch)
> 			return
> ```

Consider whether `continue` is a better choice here. Currently, if there's a single failed read, the worker silently aborts and the tunnel becomes permanently broken?


<!-- Sent from Reviewable.io -->

2024-07-01 10:04 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 4 of 7 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 113 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VxYNA9fLN2-mQQLTB:-O0hixpc4cgAIVhozJ33:bxsvzeh) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L113)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Have you considered using `remoteAddr` etc instead of `destAddr`? I find it quite confusing when related code reads the source IP and puts it in `destAddr`.
</blockquote></details>

Good idea; I'll change `source*` to `local*` and `dest*` to `remote*`
___
*[`Sources/WireGuardKitGo/router.go` line 225 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VqP5ZBEvCPqvQyISE:-O0hjCk1AMr0oXPR5p74:b-qeg0g2) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L225)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What's the purpose of the `maxOffset` subslicing?
</blockquote></details>

It's a fossil from when we thought we may be passing the buffers back to WireGuardGo. We can get rid of it.
___
*[`Sources/WireGuardKitGo/router.go` line 309 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0W0TYa3F4kQWNXWHUZ:-O0hjskC4S2Mhyo0NCtw:b61djzw) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L309)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Consider whether `continue` is a better choice here. Currently, if there's a single failed read, the worker silently aborts and the tunnel becomes permanently broken?
</blockquote></details>

Good catch. @pinkisemils , would you agree?


<!-- Sent from Reviewable.io -->

2024-07-01 11:58 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router.go` line 229 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0Vsz_R-WMx2pwbRYhy:-O0i7fP25xQkFu6KS2FA:blyz7wd) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L229)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The comment at the start of this function mentions parallel execution. But the function called here is not safe in that context, without using additional locking.
</blockquote></details>

How likely is `Read` to be executed in parallel, given that it is the interface by which the WireGuard stack reads packets from the client? Is this something we need to worry about?


<!-- Sent from Reviewable.io -->

2024-07-01 12:38 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router.go` line 229 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0Vsz_R-WMx2pwbRYhy:-O0iI0TTCamaiQU2bajo:bbciaxn) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L229)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

How likely is `Read` to be executed in parallel, given that it is the interface by which the WireGuard stack reads packets from the client? Is this something we need to worry about?
</blockquote></details>

At the moment, wireguard-go only spawns a single read worker, which (while this assumption holds) makes it safe to eschew the overhead of additional locking.  I have rephrased the comment to make this assumption explicit.


<!-- Sent from Reviewable.io -->

2024-07-01 13:56 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router.go` line 225 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VqP5ZBEvCPqvQyISE:-O0i_JHcDK4vR88jMwKA:b3emiys) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L225)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

It's a fossil from when we thought we may be passing the buffers back to WireGuardGo. We can get rid of it.
</blockquote></details>

maxOffset has now been removed.


<!-- Sent from Reviewable.io -->

2024-07-01 15:32 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 3 of 7 files reviewed, 12 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router_test.go` line 542 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0itnyg0A8q2eMcfgtw:-O0itnyg0A8q2eMcfgtx:bpt2bai) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router_test.go#L542)):*
> ```Go
> 	secondPayload := []byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
> 	thirdPayload := make([]byte, 100)
> 	rand.Read(secondPayload[:])
> ```

Wrong instance used as argument here?
___
*[`Sources/WireGuardKitGo/router_test.go` line 597 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0iux-s821fSc1XJ74F:-O0iux-s821fSc1XJ74G:btl6ubh) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router_test.go#L597)):*
> ```Go
> 		t.Fatalf("Expected to receive %v, instead got %v", secondPayload, clientBuff[:bytesRead])
> 	}
> ```

Isn't there supposed to be a `clientConnection.Write(thirdPayload)` here?


<!-- Sent from Reviewable.io -->

2024-07-01 15:43 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 225 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VqP5ZBEvCPqvQyISE:-O0iwIVc4HJw-BH-tU9F:b-dmsf74) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L225)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

maxOffset has now been removed.
</blockquote></details>

Nit: That same subslicing can be removed alltogether, since `[0:]` effectively produces the source slice unchanged.
___
*[`Sources/WireGuardKitGo/router.go` line 229 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0Vsz_R-WMx2pwbRYhy:-O0iwxu1AYHXV23sA-Zl:b-5sxtnq) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L229)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

At the moment, wireguard-go only spawns a single read worker, which (while this assumption holds) makes it safe to eschew the overhead of additional locking.  I have rephrased the comment to make this assumption explicit.
</blockquote></details>

Updated comment looks good :+1: 


<!-- Sent from Reviewable.io -->

2024-07-02 15:09 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 152 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08K2OF0VHUtsoxM_GO:-O0miJ897KmO9J8xJvnO:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/api-apple.go#L152)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Actually, nevermind, it looks like `getdtablesize` is a very old and obsolete function at this point.
Thanks for running the experiment though.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 225 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0VqP5ZBEvCPqvQyISE:-O0nlOWy4WUHG5pl6G7z:b-896fjx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L225)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Nit: That same subslicing can be removed alltogether, since `[0:]` effectively produces the source slice unchanged.
</blockquote></details>

Done
___
*[`Sources/WireGuardKitGo/router_test.go` line 542 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0itnyg0A8q2eMcfgtw:-O0nzKMw8aRgsg-hBSJH:b-886gsx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router_test.go#L542)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Wrong instance used as argument here?
</blockquote></details>

Fixed
___
*[`Sources/WireGuardKitGo/router_test.go` line 597 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0iux-s821fSc1XJ74F:-O0nzLfU9Eq6ehtD4wBz:b-886gsx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router_test.go#L597)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Isn't there supposed to be a `clientConnection.Write(thirdPayload)` here?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-07-03 08:28 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, @mvd-ows, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/go.mod` line 20 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O08GZtW1mAgH4nbO_ii:-O0rhLjR6ZQDRN8a3Gd5:b-gg4mwv) ([raw file](https://github.com/mullvad/wireguard-apple/blob/743c33351d67ddbeaccc45bb61426a927f45f6bf/Sources/WireGuardKitGo/go.mod#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This will require us moving to go 1.20, we should make sure to track that change in the mullvad codebase.
</blockquote></details>

We do need to move to Go 1.20 because of dependencies we use here.


<!-- Sent from Reviewable.io -->

2024-07-03 12:52 UTC, pinkisemils approved these changes
> Reviewed 2 of 7 files at r1, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: all files reviewed, 7 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @mvd-ows)

___
*[`Sources/WireGuardKitGo/router.go` line 309 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0W0TYa3F4kQWNXWHUZ:-O0sayhI2MZO49Sodvx-:b6n7nka) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L309)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Good catch. @pinkisemils , would you agree?
</blockquote></details>

A `continue` may well make this a busy loop. We could introduce yet another channel to relay the error back to the `Read` call to make it fail. Ideally, we would shut down both readers in that case.


<!-- Sent from Reviewable.io -->

2024-07-03 16:11 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router.go` line 309 at r10](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0W0TYa3F4kQWNXWHUZ:-O0tMSAz4wu_w1ZseNwX:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/c2cfd6d7047fbd5a06c2121d1c82a6c6963b850c/Sources/WireGuardKitGo/router.go#L309)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

A `continue` may well make this a busy loop. We could introduce yet another channel to relay the error back to the `Read` call to make it fail. Ideally, we would shut down both readers in that case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 07:20 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @acb-mv, @buggmagnet, @MarkusPettersson98, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-07-04 09:23 UTC, buggmagnet requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: all files reviewed, 7 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router_test.go` line 294 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x1Uv5DKQZ9-mT90jQ:-O0x1Uv5DKQZ9-mT90jR:b-4ra3dt) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L294)):*
> ```Go
> 
> func TestUDP(t *testing.T) {
> 	aIp := netip.AddrFrom4([4]byte{1, 2, 3, 4})
> ```

nit
A lot of the setup in these tests is very similar, which makes the tests really verbose for no reason, for instance I count this line 8 times in the file.

Is there a chance we can do a bit of refactoring to either parametrize those setups, or have a function that does the init so that the tests are easier to read ?
___
*[`Sources/WireGuardKitGo/router_test.go` line 305 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x0K0E7FeqOwFBo6uN:-O0x0K0E7FeqOwFBo6uO:b-prs5j1) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L305)):*
> ```Go
> 	b, bNet, _ := netstack.CreateNetTUN([]netip.Addr{bIp}, []netip.Addr{}, 1280)
> 
> 	// aDev := device.NewDevice(a, conn.NewStdNetBind(), device.NewLogger(device.LogLevelVerbose, ""))
> ```

Can we delete this and all the other commented code lines in this file ?
___
*[`Sources/WireGuardKitGo/router_test.go` line 531 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x24rDDqItXLwqdW0N:-O0x24rDDqItXLwqdW0O:bhnaih7) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L531)):*
> ```Go
> }
> 
> func testTcpTraffic(t *testing.T, serverNet, clientNet *netstack.Net, serverIP, clientIP netip.Addr) {
> ```

The `clientIP` parameter is not used
___
*[`Sources/WireGuardKitGo/router_test.go` line 621 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0wzn7v2C_Q7RqWsvXd:-O0wzn7v2C_Q7RqWsvXe:bdmsjkz) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L621)):*
> ```Go
> 		t.Fatalf("Failed to parse a packet header")
> 	}
> 	assert.Equal(t, header.protocol, uint8(17))
> ```

assert.Equal(t, header.protocol, tcpip.TransportProtocolNumber(17))

Same for the other protocol check in this test.
Let's also delete those comments


<!-- Sent from Reviewable.io -->

2024-07-04 13:56 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router_test.go` line 294 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x1Uv5DKQZ9-mT90jQ:-O0y1-fl8VQpr_Ym65w7:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L294)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
A lot of the setup in these tests is very similar, which makes the tests really verbose for no reason, for instance I count this line 8 times in the file.

Is there a chance we can do a bit of refactoring to either parametrize those setups, or have a function that does the init so that the tests are easier to read ?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-04 13:58 UTC, acb-mv commented
*[`Sources/WireGuardKitGo/router_test.go` line 531 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x24rDDqItXLwqdW0N:-O0y1RqO5vpq0dk97hFS:ba3dfob) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L531)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The `clientIP` parameter is not used
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2024-07-04 13:58 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router_test.go` line 305 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0x0K0E7FeqOwFBo6uN:-O0y0zUSD9OncgGaiYcw:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L305)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we delete this and all the other commented code lines in this file ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 14:05 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/router_test.go` line 621 at r13](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O0wzn7v2C_Q7RqWsvXd:-O0y3C1DDss0DYB7rMt0:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2b0bdc4c8a0cc93804724a5d6e8cc1ca7b983b91/Sources/WireGuardKitGo/router_test.go#L621)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

assert.Equal(t, header.protocol, tcpip.TransportProtocolNumber(17))

Same for the other protocol check in this test.
Let's also delete those comments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-05 08:55 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r1, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-:-O115hCf1rJYB-SUnVLk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-07-08 08:08 UTC, pinkisemils requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @MarkusPettersson98)

___
*[`Sources/WireGuardKitGo/router.go` line 306 at r15](https://reviewable.io/reviews/mullvad/wireguard-apple/10#-O12QivS4pJwG78JsETs:-O12QivS4pJwG78JsETt:b-dy5h69) ([raw file](https://github.com/mullvad/wireguard-apple/blob/0e1125314caa3aa3f338b6d7dd6b0a644aada34d/Sources/WireGuardKitGo/router.go#L306)):*
> ```Go
> 		if err != nil {
> 			r.batchPool.Put(batch)
> 			r.error = err
> ```

This is not thread safe, the other thread might not see this write until way later.


<!-- Sent from Reviewable.io -->

2024-07-08 15:51 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/10)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2024-07-09 12:43 UTC, merged