Jdcqrm the mole fork
mullvad/wireguard-apple pull request #15
Opened 2024-07-22 13:23 UTC by pinkisemils

2024-07-23 18:37 UTC, lawchingman approved these changes

2024-07-23 18:38 UTC, lawchingman approved these changes

2024-08-05 15:23 UTC, hulthe reviewed
> Reviewed 5 of 15 files at r1, 2 of 5 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 8 of 16 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 473 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y5DfXBllTxibSsi72:-O3Y5DfXBllTxibSsi73:b-mus0fz) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/api-apple.go#L473)):*
> ```Go
> 		return errBadEntryConfig
> 	}
> 	peer := device.LookupPeer(*entryPeerPubkey)
> ```

hmm. Maybe we should just add daita to the config string.
___
*[`Sources/WireGuardKitGo/Makefile` line 59 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y-fyg-e6a9Cgc9i_o:-O3Y-fyg-e6a9Cgc9i_p:bjc60vu) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/Makefile#L59)):*
> ```Makefile
> 			  CARGO=$(HOME)/.cargo/bin/cargo \
> 			  TARGET=$(RUST_$(1))-apple-$(RUST_TARGET_$(PLATFORM_NAME)) \
> 			  make -C wireguard-go/maybenot/crates/maybenot-ffi
> ```

sneaky space characters
___
*[`Sources/WireGuardKitGo/router.go` line 25 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y07Y78O747c9CGxLr:-O3Y07Y78O747c9CGxLs:b-byk6ti) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L25)):*
> ```Go
> // Currently, WireGuardGo sends buffers one at a time, so this is 1, though the API says that
> // this is not set in stone.
> const expectedBufferCount = 128
> ```

Minor: The comment claims that this value is `1`.
___
*[`Sources/WireGuardKitGo/router.go` line 204 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XX46r-KDOipZ5rB2T:-O3XX46sAY87kiCT02b2:b-w4u3gy) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L204)):*
> ```Go
> 	case batch, ok = <-r.read.rxChannel:
> 		defer func() {
> 			batch.completion <- batch
> ```

Looks like `batch` could potentially be `nil` if the channel is closed. Then this would panic.
___
*[`Sources/WireGuardKitGo/router.go` line 208 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XYAXy9b7iatsFUV2I:-O3XYAXy9b7iatsFUV2J:bppuv0y) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L208)):*
> ```Go
> 		if !ok {
> 			return 0, errors.New("reader shut down")
> 		}
> ```

I'm confused as to what this case is doing. Why are we receiving PacketBatches here, only to immediately send them back to `readWorker` without touching them?
___
*[`Sources/WireGuardKitGo/router.go` line 298 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XzjhR4rDMTT2pgB01:-O3XzjhR4rDMTT2pgB02:b-pjecmf) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L298)):*
> ```Go
> 		case batch = <-completion:
> 			batch.packet = buffer
> 			break
> ```

I believe break is redundant here. Did you mean to break the for-loop?


<!-- Sent from Reviewable.io -->

2024-08-07 13:52 UTC, buggmagnet reviewed
> Reviewed 8 of 15 files at r1, 2 of 5 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @hulthe, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/Makefile` line 59 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y-fyg-e6a9Cgc9i_o:-O3gRgur89WfXQaKkJpN:b-896fjx) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/Makefile#L59)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

sneaky space characters
</blockquote></details>

Done
___
*[`Sources/WireGuardKitGo/router.go` line 25 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y07Y78O747c9CGxLr:-O3gRoKh275MAfilv2q7:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L25)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Minor: The comment claims that this value is `1`.
</blockquote></details>

Done
___
*[`Sources/WireGuardKitGo/router.go` line 204 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XX46r-KDOipZ5rB2T:-O3gSTd-Dsp7s1in8nKO:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L204)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Looks like `batch` could potentially be `nil` if the channel is closed. Then this would panic.
</blockquote></details>

Done
___
*[`Sources/WireGuardKitGo/router.go` line 298 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XzjhR4rDMTT2pgB01:-O3guSctDuRK73hHYoUr:biag5k3) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L298)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I believe break is redundant here. Did you mean to break the for-loop?
</blockquote></details>

The `break` statements are indeed [redundant](https://go.dev/ref/spec#Break_statements) here.
I'll remove them.

I don't think the original intention was to break out of the for loop either.


<!-- Sent from Reviewable.io -->

2024-08-07 15:51 UTC, hulthe requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/Makefile` line 82 at r7](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3hX0iACCObVwOF9N0N:-O3hX0iACCObVwOF9N0O:b-8n2795) ([raw file](https://github.com/mullvad/wireguard-apple/blob/63b3aeb6e2da87d426e93cdd176a9dab92896409/Sources/WireGuardKitGo/Makefile#L82)):*
> ```Makefile
> 
> libmaybenot.a: $(wildcard maybenot/*)
> 	make --directory wireguard-go/maybenot/crates/maybenot-ffi/
> ```

Should this not specify DESTINATION? It looks like this just builds libmaybenot.a and places it in the `maybenot-ffi` folder.
```
make --directory wireguard-go/maybenot/crates/maybenot-ffi/ DESTINATION=$(CURDIR)
```
___
*[`Sources/WireGuardKitGo/router.go` line 25 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3Y07Y78O747c9CGxLr:-O3hRyCe7BqN_boy0EPf:bjth9nd) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L25)):*
> Currently, WireGuardGo sends buffers one at a time, so this is 128

Ah yes, makes perfect sense


<!-- Sent from Reviewable.io -->

2024-08-08 12:47 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @hulthe, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/Makefile` line 82 at r7](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3hX0iACCObVwOF9N0N:-O3lJuR73IsJ4c2E32pJ:b1d7x4j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/63b3aeb6e2da87d426e93cdd176a9dab92896409/Sources/WireGuardKitGo/Makefile#L82)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Should this not specify DESTINATION? It looks like this just builds libmaybenot.a and places it in the `maybenot-ffi` folder.
```
make --directory wireguard-go/maybenot/crates/maybenot-ffi/ DESTINATION=$(CURDIR)
```
</blockquote></details>

Turns out this was not needed, so I deleted the rule instead. 


<!-- Sent from Reviewable.io -->

2024-08-08 13:19 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @hulthe, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/router.go` line 208 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XYAXy9b7iatsFUV2I:-O3m3wgK4JQhAu6y5tUM:bp1sr2a) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L208)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I'm confused as to what this case is doing. Why are we receiving PacketBatches here, only to immediately send them back to `readWorker` without touching them?
</blockquote></details>

AFAICT it's because we're multiplexing our own (virtual) traffic alongside the (real) user traffic, this helps us redirect packets based on whether they are virtual or real ones.


<!-- Sent from Reviewable.io -->

2024-08-12 08:52 UTC, hulthe approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/15)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @Serock3)

___
*[`Sources/WireGuardKitGo/Makefile` line 82 at r7](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3hX0iACCObVwOF9N0N:-O3m9Mgd8o2OmTGHFoNg:b-8axsai) ([raw file](https://github.com/mullvad/wireguard-apple/blob/63b3aeb6e2da87d426e93cdd176a9dab92896409/Sources/WireGuardKitGo/Makefile#L82)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Turns out this was not needed, so I deleted the rule instead.
</blockquote></details>

Aight
___
*[`Sources/WireGuardKitGo/router.go` line 208 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/15#-O3XYAXy9b7iatsFUV2I:-O44mHm13EOK3kWTDNrD:b-lj7qil) ([raw file](https://github.com/mullvad/wireguard-apple/blob/9026c6a1533ec31c686c719765206f43f12983a6/Sources/WireGuardKitGo/router.go#L208)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

AFAICT it's because we're multiplexing our own (virtual) traffic alongside the (real) user traffic, this helps us redirect packets based on whether they are virtual or real ones.
</blockquote></details>

Ah. I was just confused as to how defer works. This makes more sense to me now.


<!-- Sent from Reviewable.io -->

2024-08-12 11:11 UTC, merged