Escape paths in Makefile
mullvad/wireguard-apple pull request #27
Opened 2024-09-23 11:08 UTC by pinkisemils

When Xcode is ran from a path with whtespace in it, these unescaped paths fail the build.

2024-09-23 12:20 UTC, MarkusPettersson98 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @pinkisemils)

___
*[`Sources/WireGuardKitGo/Makefile` line 60 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-O7TolZC0kHJjgupBkEi:-O7TolZC0kHJjgupBkEj:b-1i6d7j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/87f7560c6eb61c7918fd97de84bae54426319617/Sources/WireGuardKitGo/Makefile#L60)):*
> ```Makefile
> 			DESTINATION="$(BUILT_PRODUCTS_DIR)" \
> 			PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:" \
> 			CARGO=$(HOME)/.cargo/bin/cargo \
> ```

Should this path also be escaped?



_Code quote:_
```Makefile
	CARGO=$(HOME)/.cargo/bin/cargo \
```


<!-- Sent from Reviewable.io -->

2024-09-23 14:52 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-:-O7UMfXp4-7KXc57kToy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`Sources/WireGuardKitGo/Makefile` line 60 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-O7TolZC0kHJjgupBkEi:-O7UMGDL5-NX8yTlT0B5:blgpyr9) ([raw file](https://github.com/mullvad/wireguard-apple/blob/87f7560c6eb61c7918fd97de84bae54426319617/Sources/WireGuardKitGo/Makefile#L60)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should this path also be escaped?
</blockquote></details>

if you can have a `$HOME` that contains spaces (aka a username that has spaces inside) then probably yes I would say


<!-- Sent from Reviewable.io -->

2024-09-24 10:43 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`Sources/WireGuardKitGo/Makefile` line 60 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-O7TolZC0kHJjgupBkEi:-O7YcCT77B52YNbHNWF8:b-x4ceq7) ([raw file](https://github.com/mullvad/wireguard-apple/blob/87f7560c6eb61c7918fd97de84bae54426319617/Sources/WireGuardKitGo/Makefile#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

if you can have a `$HOME` that contains spaces (aka a username that has spaces inside) then probably yes I would say
</blockquote></details>

Yes, will fix.


<!-- Sent from Reviewable.io -->

2024-09-24 10:46 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`Sources/WireGuardKitGo/Makefile` line 60 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-O7TolZC0kHJjgupBkEi:-O7YcpFn-M8Mi3l7VZZi:b3xzkh7) ([raw file](https://github.com/mullvad/wireguard-apple/blob/87f7560c6eb61c7918fd97de84bae54426319617/Sources/WireGuardKitGo/Makefile#L60)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yes, will fix.
</blockquote></details>

Is fixed.


<!-- Sent from Reviewable.io -->

2024-09-24 11:27 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-:-O7YmFbJ3O3BIaxT0Aq0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-09-24 11:46 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/27#-:-O7Yqm-O4pdS7I4OyIfY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-09-24 13:51 UTC, merged