Fix race conditions in pinger
mullvad/wireguard-apple pull request #31
Opened 2024-10-24 05:54 UTC by buggmagnet

This PR fixes a race condition in accessing the WireguardAdapter when sending and receiving pings.
It also changes the ability to open and close the socket used for pinging from `public` to `private`.

2024-10-24 10:56 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @pinkisemils)

___
*[`Sources/WireGuardKitTypes/TunnelConfiguration.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-O9y9sT0AATl5bHTXaxU:-O9y9sT0AATl5bHTXaxV:b6m369q) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKitTypes/TunnelConfiguration.swift#L11)):*
> ```Swift
>     public var interface: InterfaceConfiguration
>     public let peers: [PeerConfiguration]
>     public let pingableGateway: IPv4Address?
> ```

Is there any point where we wouldn't want a pingable gateway ?
Or is it to maintain compatibility with vanilla WireGuard ?


<!-- Sent from Reviewable.io -->

2024-10-24 14:51 UTC, pinkisemils reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @buggmagnet)

___
*[`Sources/WireGuardKitTypes/TunnelConfiguration.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-O9y9sT0AATl5bHTXaxU:-O9z-ToWC3nVk57Mu3wW:bdoqj2n) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKitTypes/TunnelConfiguration.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Is there any point where we wouldn't want a pingable gateway ?
Or is it to maintain compatibility with vanilla WireGuard ?
</blockquote></details>

Only to maintain compatibility with vanilla Wireguard/make the least intrusive change possible.


<!-- Sent from Reviewable.io -->

2024-11-04 09:56 UTC, rablador requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqTLsh0jj6I-mROv8q):*
Nit: Ping able
___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 457 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqWfza8ByBu3E3c9uZ:-OAqWfza8ByBu3E3c9u_:b-lo1f6i) ([raw file](https://github.com/mullvad/wireguard-apple/blob/afb345188c187dddafae0f9e27c5466be11451c2/Sources/WireGuardKit/WireGuardAdapter.swift#L457)):*
> ```Swift
>         } else {
>             wgTurnOnIAN(exitWgConfig, tunnelFileDescriptor, privateAddr, daita?.machines ?? nil, daita?.maxEvents ?? 0, daita?.maxActions ?? 0)
> //            wgTurnOn(exitWgConfig, tunnelFileDescriptor, daita?.machines ?? nil, daita?.maxEvents ?? 0, daita?.maxActions ?? 0)
> ```

This is the only place calling `wgTurnOn` (or rather it was). Is it not to be used anymore?
___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 605 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqXmtm22aqH8Gg2tjv:-OAqXmtm22aqH8Gg2tjw:bz6z7sw) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKit/WireGuardAdapter.swift#L605)):*
> ```Swift
> 
>                 let gatewayAddress = IPv4Address("10.64.0.1")!
>                 try self.openICMP(address: gatewayAddress)
> ```

Can't we get the gateway from the `settingsGenerator -> tunnelconfig` here?
___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 663 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAq_9M6CPoQPFl57_9j:-OAq_9M6CPoQPFl57_9k:b-9g806y) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKit/WireGuardAdapter.swift#L663)):*
> ```Swift
>     public func receiveICMP() throws -> Int32 {
>         dispatchPrecondition(condition: .notOnQueue(workQueue))
>         let tunnelSocketPair = try workQueue.sync {
> ```

Nit: We could name the tuple params for readability.


<!-- Sent from Reviewable.io -->

2024-11-04 12:11 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: all files reviewed, 4 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 605 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqXmtm22aqH8Gg2tjv:-OAr1xdx99gUC2zTiuJI:b3pkke6) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKit/WireGuardAdapter.swift#L605)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can't we get the gateway from the `settingsGenerator -> tunnelconfig` here?
</blockquote></details>

Good catch !
___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 663 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAq_9M6CPoQPFl57_9j:-OAr4Vdt-DQMHmHKQiWU:b-dnldtc) ([raw file](https://github.com/mullvad/wireguard-apple/blob/b7d280b42bd5899acaa3f2a5c569c50dda2c608f/Sources/WireGuardKit/WireGuardAdapter.swift#L663)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: We could name the tuple params for readability.
</blockquote></details>

Great idea !


<!-- Sent from Reviewable.io -->

2024-11-04 13:47 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-04 14:25 UTC, acb-mv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 457 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqWfza8ByBu3E3c9uZ:-OArYj7xDAgAgNiOL0sd:buvcj9i) ([raw file](https://github.com/mullvad/wireguard-apple/blob/afb345188c187dddafae0f9e27c5466be11451c2/Sources/WireGuardKit/WireGuardAdapter.swift#L457)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is the only place calling `wgTurnOn` (or rather it was). Is it not to be used anymore?
</blockquote></details>

If we've switched over to IAN, then the legacy `wgTurnOn` is obsolete. In which case, we should delete it and probably give its name to `wgTurnOnIAN`.


<!-- Sent from Reviewable.io -->

2024-11-04 14:46 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/31)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 457 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/31#-OAqWfza8ByBu3E3c9uZ:-OArd8z4DVBx6oOEU0Ek:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/afb345188c187dddafae0f9e27c5466be11451c2/Sources/WireGuardKit/WireGuardAdapter.swift#L457)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

If we've switched over to IAN, then the legacy `wgTurnOn` is obsolete. In which case, we should delete it and probably give its name to `wgTurnOnIAN`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-04 14:48 UTC, merged